#ifndef CONFIG_H
#define CONFIG_H

#define MRMATHCPP_PROJECT_NAME  "@CMAKE_PROJECT_NAME@"

#define MRMATHCPP_CONFIG_DATE   "@MRMATHCPP_CONFIG_DATE@"
#define MRMATHCPP_CONFIG_OS     "@CMAKE_HOST_SYSTEM_VERSION@"
#define MRMATHCPP_CONFIG_CMVER  "@CMAKE_VERSION@"
#define MRMATHCPP_CONFIG_ARCH   "@CMAKE_HOST_SYSTEM_PROCESSOR@"
#define MRMATHCPP_CONFIG_ENDIAN "@CMAKE_CXX_BYTE_ORDER@"
#define MRMATHCPP_CONFIG_COMPID "@CMAKE_CXX_COMPILER_ID@"

#define MRMATHCPP_VERSION       "@ProjName_VERSION@"
#define MRMATHCPP_VERSION_MAJOR @ProjName_VERSION_MAJOR@
#define MRMATHCPP_VERSION_MINOR @ProjName_VERSION_MINOR@
#define MRMATHCPP_VERSION_PATCH @ProjName_VERSION_PATCH@
#define MRMATHCPP_VERSION_TWEAK @ProjName_VERSION_TWEAK@
#define MRMATHCPP_VERSION_TAG   "v@ProjName_VERSION@"
#define MRMATHCPP_VERSION_DATE  "@MRMATHCPP_VERSION_DATE@"

#define MRMATHCPP_FOUND_DOXYGEN @MRMATHCPP_FOUND_DOXYGEN@
#define MRMATHCPP_FOUND_BTEST   @MRMATHCPP_FOUND_BTEST@
#define MRMATHCPP_FOUND_MRASTER @MRMATHCPP_FOUND_MRASTER@

#define MRMATHCPP_OPT_DOXYGEN   @MRMATHCPP_OPT_DOXYGEN@
#define MRMATHCPP_OPT_BTEST     @MRMATHCPP_OPT_BTEST@
#define MRMATHCPP_OPT_MRASTER   @MRMATHCPP_OPT_MRASTER@

#include <string>

std::string ProjName_version_string() { return std::string(MRMATHCPP_VERSION_TAG) + " -- " + std::string(MRMATHCPP_VERSION_DATE); }

int ProjName_version_major() { return MRMATHCPP_VERSION_MAJOR; }
int ProjName_version_minor() { return MRMATHCPP_VERSION_MINOR; }
int ProjName_version_patch() { return MRMATHCPP_VERSION_PATCH; }
int ProjName_version_tweak() { return MRMATHCPP_VERSION_TWEAK; }

bool ProjName_support_mraster() { return MRMATHCPP_OPT_MRASTER; }

#endif
