#ifndef CONFIG_H
#define CONFIG_H

#define MRMATHCPP_PROJECT_NAME  "@CMAKE_PROJECT_NAME@"

#define MRMATHCPP_CONFIG_DATE   "@MRMATHCPP_CONFIG_DATE@"
#define MRMATHCPP_CONFIG_OS     "@CMAKE_HOST_SYSTEM_VERSION@"
#define MRMATHCPP_CONFIG_CMVER  "@CMAKE_VERSION@"
#define MRMATHCPP_CONFIG_ARCH   "@CMAKE_HOST_SYSTEM_PROCESSOR@"
#define MRMATHCPP_CONFIG_ENDIAN "@CMAKE_CXX_BYTE_ORDER@"
#define MRMATHCPP_CONFIG_COMPID "@CMAKE_CXX_COMPILER_ID@"

#define MRMATHCPP_VERSION       "@MRMathCPP_VERSION@"
#define MRMATHCPP_VERSION_MAJOR @MRMathCPP_VERSION_MAJOR@
#define MRMATHCPP_VERSION_MINOR @MRMathCPP_VERSION_MINOR@
#define MRMATHCPP_VERSION_PATCH @MRMathCPP_VERSION_PATCH@
#define MRMATHCPP_VERSION_TWEAK @MRMathCPP_VERSION_TWEAK@
#define MRMATHCPP_VERSION_TAG   "v@MRMathCPP_VERSION@"
#define MRMATHCPP_VERSION_DATE  "@MRMATHCPP_VERSION_DATE@"

#define MRMATHCPP_FOUND_DOXYGEN @MRMATHCPP_FOUND_DOXYGEN@
#define MRMATHCPP_FOUND_GTEST   @MRMATHCPP_FOUND_GTEST@

#define MRMATHCPP_OPT_DOXYGEN   @MRMATHCPP_OPT_DOXYGEN@
#define MRMATHCPP_OPT_GTEST     @MRMATHCPP_OPT_GTEST@

#include <string>

std::string MRMathCPP_version_string() { return std::string(MRMATHCPP_VERSION_TAG) + " -- " + std::string(MRMATHCPP_VERSION_DATE); }

int MRMathCPP_version_major() { return MRMATHCPP_VERSION_MAJOR; }
int MRMathCPP_version_minor() { return MRMATHCPP_VERSION_MINOR; }
int MRMathCPP_version_patch() { return MRMATHCPP_VERSION_PATCH; }
int MRMathCPP_version_tweak() { return MRMATHCPP_VERSION_TWEAK; }

bool MRMathCPP_support_mraster() { return MRMATHCPP_OPT_MRASTER; }

#endif
