#ifndef CONFIG_H
#define CONFIG_H

#define PROJNAME_PROJECT_NAME  "@CMAKE_PROJECT_NAME@"

#define PROJNAME_CONFIG_DATE   "@PROJNAME_CONFIG_DATE@"
#define PROJNAME_CONFIG_OS     "@CMAKE_HOST_SYSTEM_VERSION@"
#define PROJNAME_CONFIG_CMVER  "@CMAKE_VERSION@"
#define PROJNAME_CONFIG_ARCH   "@CMAKE_HOST_SYSTEM_PROCESSOR@"
#define PROJNAME_CONFIG_ENDIAN "@CMAKE_CXX_BYTE_ORDER@"
#define PROJNAME_CONFIG_COMPID "@CMAKE_CXX_COMPILER_ID@"

#define PROJNAME_VERSION       "@ProjName_VERSION@"
#define PROJNAME_VERSION_MAJOR @ProjName_VERSION_MAJOR@
#define PROJNAME_VERSION_MINOR @ProjName_VERSION_MINOR@
#define PROJNAME_VERSION_PATCH @ProjName_VERSION_PATCH@
#define PROJNAME_VERSION_TWEAK @ProjName_VERSION_TWEAK@
#define PROJNAME_VERSION_TAG   "v@ProjName_VERSION@"
#define PROJNAME_VERSION_DATE  "@PROJNAME_VERSION_DATE@"

#define PROJNAME_FOUND_DOXYGEN @PROJNAME_FOUND_DOXYGEN@
#define PROJNAME_FOUND_BTEST   @PROJNAME_FOUND_BTEST@
#define PROJNAME_FOUND_MRASTER @PROJNAME_FOUND_MRASTER@

#define PROJNAME_OPT_DOXYGEN   @PROJNAME_OPT_DOXYGEN@
#define PROJNAME_OPT_BTEST     @PROJNAME_OPT_BTEST@
#define PROJNAME_OPT_MRASTER   @PROJNAME_OPT_MRASTER@

#include <string>

std::string ProjName_version_string() { return std::string(PROJNAME_VERSION_TAG) + " -- " + std::string(PROJNAME_VERSION_DATE); }

int ProjName_version_major() { return PROJNAME_VERSION_MAJOR; }
int ProjName_version_minor() { return PROJNAME_VERSION_MINOR; }
int ProjName_version_patch() { return PROJNAME_VERSION_PATCH; }
int ProjName_version_tweak() { return PROJNAME_VERSION_TWEAK; }

bool ProjName_support_mraster() { return PROJNAME_OPT_MRASTER; }

#endif
