* MRMathCPP

MRMathCPP is a collection of very simple math routines very carefully implemented.

This library started as a way to render common constructs like ~abs(x1-x2)<eps~ into more readable code like ~fc::near(x1, x2, eps)~.
Over time it grew to contain much more, but I've tried to keep the focus on simple stuff like =sgn= and =max4= that I use over and over
again across several code bases.

 - =MRMathBPLY.hpp=:  Bivariate Polynomials
 - =MRMathCPLX.hpp=:  Complex Numbers
 - =MRMathESGN.hpp=:  Enumerated Signs for SDF Function Tests
 - =MRMathFC.hpp=:  Floating Point Comparisons
 - =MRMathIVL.hpp=:  Numeric Intervals
 - =MRMathLINM.hpp=:  One Dimensional Linear Transforms
 - =MRMathODE.hpp=:  ODE IVP Solvers
 - =MRMathODR.hpp=:  Numerical Order
 - =MRMathSFUN.hpp=:  Special Functions
 - =MRMathSTR.hpp=:  Formatting & Strings
 - =MRMathUPLY.hpp=:  Univariate Polynomials
 - =MRMathVEC.hpp=:  Real & complex vectors using std::array

* Documentation

   - API Docs: https://www.mitchr.me/SS/MRMathCPP/doc-lib/autodocs/html/index.html
   - Change log: https://richmit.github.io/MRMathCPP/changelog.html

* Use

MRMathCPP is a "/header only/" C++ library so there is nothing to build.  Simply use the headers you need.

If you are using an IDE, then simply add the =.hpp= files in the =lib/= directory to your project's sources.  If you are using
GCC/Clang on the command line, then add the =lib/= directory to your include path with the =-I= compiler option.  

If you wish to use this library from a CMake project, then take a look at
[[https://github.com/richmit/MRMathCPP/blob/main/IncludeMRMathCPPLib.cmake][IncludeMRMathCPPLib.cmake]].

Note that you can include just the specific headers you need in your code, or include them all with =MRMathCPP.hpp=.

* Generate Local Documentation

I use the sequence of commands below to generate the project documentation.  Something similar should work if you wish to 
produce local documentation:
  - First make sure you have Doxygen installed.  
  - Replace "~MSYS Makefiles~" in the sequence below with your preferred generator.  
  - Replace "~edge~" with your browser of choice.  

The result should be identical to the
[[https://www.mitchr.me/SS/MRMathCPP/doc-lib/autodocs/html/index.html][published documentation]].  

#+begin_src sh
cmake -G "MSYS Makefiles" -B build --fresh
cmake --build build --parallel 8 -t doc-lib
edge build/doc-lib/autodocs/html/index.html 
#+end_src

* Unit Tests

The unit tests contained in the ~utests/~ directory provide a good source of examples for many of the functions.  You can run the unit
tests with something like this (run from the root of the repository):

#+begin_src sh
cmake -G "MSYS Makefiles" -B build --fresh
cmake --build build --parallel 8 -t utests
cmake --build build --parallel 8 -t test
#+end_src

Note: Replace "~MSYS Makefiles~" in the command sequence above with your preferred generator.

HAVE FUN!

-mitch


