* MRMathCPP

MRMathCPP is a collection of very simple math routines very carefully
implemented.

This library started as a way to render common constructs like
~abs(x1-x2)<eps~ into more readable code like ~fc::near(x1, x2, eps)~.
Over time it grew to contain much more, but I've tried to keep the
focus on simple stuff like =sgn= and =max4= that I use over and over
again across several code bases.

* Documentation

   https://www.mitchr.me/SS/MRMathCPP/doc-lib/autodocs/html/index.html

* Use

If you are using an IDE, then simply add the =lib/= directory, or the
=.hpp= files, to your project.  If you are using GCC/Clang on the
command line, then add the =lib/= directory to your include path with
the =-I= compiler option.  To use from CMake, see the file
[[https://github.com/richmit/MRMathCPP/blob/main/IncludeMRMathCPPLib.cmake][=IncludeMRMathCPPLib.cmake=]]
at the root of the repository.

In your code you can include just the specific headers you need, or
include them all by with =MRMathCPP.hpp=.

HAVE FUN!

-mitch

